### ISSUE TITLE
Problems installing the package on macOS M1 chip

### ISSUE THREAD

**Issue by davidgarciatwenix** [googleapis/python-bigquery-pandas#588] opened 2022-11-15 15:47 UTC
Hi,

I am having problems to install this package on a macos with M1 chip.

The error:
Could not find <Python.h>. This could mean the following:
        * You're on Ubuntu and haven't run `apt-get install python3-dev`.
        * You're on RHEL/Fedora and haven't run `yum install python3-devel` or
          `dnf install python3-devel` (make sure you also have redhat-rpm-config
          installed)
        * You're on Mac OS X and the usual Python framework was somehow corrupted
          (check your environment variables or try re-installing?)
        * You're on Windows and your Python installation was somehow corrupted
          (check your environment variables or try re-installing?)
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> grpcio

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

#### Environment details

  - OS type and version: MacOS 12.4 (chip M1)
  - Python version: Python 3.10.0
  - pip version: pip 22.3.1 
  

Thanks!

**Comment by max-sixty** [comment] 2023-01-12 02:53
This ilke a problem installing `grpcio`, not with `pandas-gbq`. Does `pip install grpcio` work?

**Comment by leahecole** [comment] 2023-05-15 17:45
I just tried to reproduce this on an M1 with pandas-gbq==0.17.9 (the closest release to when this bug was opened) and I could not. @davidgarciatwenix I'm going to close this for now, but please reopen with more information (exact command you're running, requirements.txt file if being used) if the issue is still occurring!

**Closed by leahecole** 2023-05-15 17:45 UTC
Labels: api: bigquery
