### ISSUE TITLE
Null values in GBQ not correctly converted to NaN in pandas

### ISSUE THREAD

**Issue by snauhaus** [googleapis/python-bigquery-pandas#408] opened 2021-10-14 14:26 UTC
I'm experiencing an issue where the data frame returned by `pd.read_gbq` contains null values that are not recognized by Pandas.  That is, `df.loc[df.foobar.isnull()]` or `df.loc[df.foobar.isna()]` returns rows where `foobar` is actually not null/na. And, vice versa, for `notnull()` and `notna()` the same happens. 

The problem does not exist when first downloading from GBQ as csv and importing that file. 

Attached two screenshots of the issue. Unfortunately I cannot provide a data example. 

<img width="709" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/6086231/137337927-db1ddb23-d73d-41f0-bb77-201d116a1a66.png">
<img width="725" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/6086231/137337930-72780721-1fae-4c19-b56b-e0f4834e7c48.png">

**Comment by tswast** [comment] 2021-11-17 17:05
Closing, as I'm not able to reproduce without more information.

**Closed by tswast** 2021-11-17 17:05 UTC
Labels: type: question, api: bigquery
