### ISSUE TITLE
Pandas GBQ Integration Tests

### ISSUE THREAD

**Issue by alimcmaster1** [googleapis/python-bigquery-pandas#309] opened 2020-02-06 01:00 UTC
Pandas CI -> [test_gbq.py](https://github.com/pandas-dev/pandas/blob/master/pandas/io/gbq.py) can be flakey.

Following API call times out:
```
address = ('bigquery.googleapis.com', 443), timeout = 60, source_address = None
error = NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f25022abf98>: Failed to establish a new connection: [Errno 110] Connection timed out',)
```
Called from https://github.com/pydata/pandas-gbq/blob/master/pandas_gbq/gbq.py#L1312

Can we allow `to_gbq` to set a more generous timeout? Or any other solution here?

Example test failures on our master branch:

e.g : https://travis-ci.org/pandas-dev/pandas/jobs/646554600?utm_medium=notification&utm_source=github_status
and
https://travis-ci.org/pandas-dev/pandas/jobs/646597032?utm_medium=notification&utm_source=github_status

cc @jreback @tswast

**Comment by tswast** [comment] 2020-02-07 16:10
It appears to be `create_dataset` that is timing out. 60 seconds feels like an unreasonably long time for dataset creation, so this feels like a bad backend release or just a network flake to me.

How often are these errors showing up?

**Comment by alimcmaster1** [comment] 2020-02-07 18:59
Thanks @tswast 

Much more frequently than normal - several examples today.

Recent example:

https://travis-ci.org/pandas-dev/pandas/jobs/647143875?utm_medium=notification&utm_source=github_status

**Comment by tswast** [comment] 2020-02-07 19:24
I did some digging. https://github.com/googleapis/google-cloud-python/pull/10219 added a default timeout to all requests. It seems the 60 seconds default was not high enough. Talking with some teammates at Google to see what might be causing this and what a more realistic timeout should be.

**Comment by alimcmaster1** [comment] 2020-02-08 13:46
Aah thanks very much for the investigation @tswast - much appreciated! Let us know if there is anything we should do on our side.

**Comment by tswast** [comment] 2020-02-11 19:29
@plamut believes this should be fixed in the latest version of the `google-auth` library.

**Comment by plamut** [comment] 2020-02-11 19:57
I would try with `google-auth>=1.11.0`, but it might not fix (all) timeout issues, especially if an unnecessary timeout is raised in a different place (it might actually happen in the BigQuery client itself, but would need to investigate a bit deeper to confirm 100%).

**Comment by plamut** [comment] 2020-03-17 15:32
How often can the flakiness be observed, and how easy/difficult is to reproduce it locally?

Also, would it be feasible to set up a CI check that would run the tests with `google-auth>=1.11.0` and the current development version of `google-cloud-bigquery`? Both of these contain a few changes to the timeout-related logic, which might have fixed this already.

**Comment by tswast** [comment] 2021-11-30 22:07
Marking as a duplicate of https://github.com/googleapis/python-bigquery-pandas/issues/418

**Closed by tswast** 2021-11-30 22:07 UTC
Labels: type: question, api: bigquery
