### ISSUE TITLE
in .to_gbq() if_exists ='replace' is  not working ideally it should truncate and replace instead its appending to existing tables

### ISSUE THREAD

**Issue by anujsh61** [googleapis/python-bigquery-pandas#668] opened 2023-08-28 19:05 UTC
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-bigquery-pandas/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version:
  - Python version: `python --version`
  - pip version: `pip --version`
  - `pandas-gbq` version: `pip show pandas-gbq`

#### Steps to reproduce

  1. ?
  2. ?

#### Code example

```python
# example
```

#### Stack trace
```
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by tswast** [comment] 2023-09-21 20:31
Thanks for the report! I'm going to mark this as a duplicate of https://github.com/googleapis/python-bigquery-pandas/issues/670 which I suspect is related to the same problem.

**Closed by tswast** 2023-09-21 20:31 UTC
Labels: api: bigquery
