### ISSUE TITLE
to_dataframe() does not execute the query in BigQuery when installing the package pandas-gbq 

### ISSUE THREAD

**Issue by eliottiti** [googleapis/python-bigquery-pandas#728] opened 2024-01-31 07:19 UTC
The installation of the pandas-gbq library causes malfunctions in my BigQuery client, preventing the proper execution of queries on BigQuery when using the to_dataframe() method. All i can say is that the query is never send to bigQuery console because i cannot see it on the job history.
I have no idea how to fix it, i tried several version of python and packages but the root cause seems somewhere else. 

#### Environment details
  - MAC pro M3 with sonoma 14.2.1
  - python  3.10.4
  - pip 23.3.2
  - pandas-gbq==0.20.0

#### Steps to reproduce

  1. Create new python env and install  pandas, google-cloud-bigquery, db-types
  2. initialize the bigquery client  and import any table with the command line `df = client.query(query).to_dataframe()`. At this step, everything work
  3. in the same env, install pandas-gbq 
  4. We i try to reproduce step 2, the connection to bigquery with the client is working  but the method `to_dataframe` does not execute the query (ie i cannot find it on the job history in Big query console (on GCP plateform).  here is the error I get after waiting some time (full version bellow in stack trace):
 ```
google.api_core.exceptions.ServiceUnavailable: 503 DNS resolution failed for bigquerystorage.googleapis.com:443: C-ares status is not ARES_SUCCESS qtype=A name=bigquerystorage.googleapis.com is_balancer=0: DNS query cancelled
``` 

#### Code example

```python
from google.cloud import bigquery
client = bigquery.Client()
query = """ select  2 +2 as toto """
df = client.query(query).to_dataframe()
```

#### Stack trace
```
Traceback (most recent call last):
  File "/Users/Eliott/envs/titi/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 79, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/Eliott/envs/titi/lib/python3.10/site-packages/grpc/_channel.py", line 1160, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/Eliott/envs/titi/lib/python3.10/site-packages/grpc/_channel.py", line 1003, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed for bigquerystorage.googleapis.com:443: C-ares status is not ARES_SUCCESS qtype=A name=bigquerystorage.googleapis.com is_balancer=0: DNS query cancelled"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-01-31T08:13:56.912148+01:00", grpc_status:14, grpc_message:"DNS resolution failed for bigquerystorage.googleapis.com:443: C-ares status is not ARES_SUCCESS qtype=A name=bigquerystorage.googleapis.com is_balancer=0: DNS query cancelled"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/Eliott/envs/titi/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/Users/Eliott/envs/titi/lib/python3.10/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/Users/Eliott/envs/titi/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 81, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 DNS resolution failed for bigquerystorage.googleapis.com:443: C-ares status is not ARES_SUCCESS qtype=A name=bigquerystorage.googleapis.com is_balancer=0: DNS query cancelled

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Eliott/envs/titi/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1893, in to_dataframe
    return query_result.to_dataframe(
  File "/Users/Eliott/envs/titi/lib/python3.10/site-packages/google/cloud/bigquery/table.py", line 2257, in to_dataframe
    record_batch = self.to_arrow(
  File "/Users/Eliott/envs/titi/lib/python3.10/site-packages/google/cloud/bigquery/table.py", line 1927, in to_arrow
    for record_batch in self.to_arrow_iterable(
  File "/Users/Eliott/envs/titi/lib/python3.10/site-packages/google/cloud/bigquery/table.py", line 1790, in _to_page_iterable
    yield from result_pages
  File "/Users/Eliott/envs/titi/lib/python3.10/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 817, in _download_table_bqstorage
    session = bqstorage_client.create_read_session(
  File "/Users/Eliott/envs/titi/lib/python3.10/site-packages/google/cloud/bigquery_storage_v1/services/big_query_read/client.py", line 636, in create_read_session
    response = rpc(
  File "/Users/Eliott/envs/titi/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/Eliott/envs/titi/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/Users/Eliott/envs/titi/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/Eliott/envs/titi/lib/python3.10/site-packages/google/api_core/retry/retry_base.py", line 221, in _retry_error_helper
    raise final_exc from source_exc
google.api_core.exceptions.RetryError: Timeout of 600.0s exceeded, last exception: 503 DNS resolution failed for bigquerystorage.googleapis.com:443: C-ares status is not ARES_SUCCESS qtype=A name=bigquerystorage.googleapis.com is_balancer=0: DNS query cancelled
```

**Comment by Linchin** [comment] 2024-01-31 23:48
Hi @eliottiti, from the error log, it seems to be a network issue - the DNS has trouble resolving the BigQuery endpoint:
> exceptions.ServiceUnavailable: 503 DNS resolution failed for bigquerystorage.googleapis.com:443

I wasn't able to reproduce, but by googling I find many similar questions people have raised. I think it's worth a try to upgrade all your packages to the latest version, and try out stuff like setting env vars as in https://github.com/grpc/grpc/issues/34709.

I will close this issue, but feel free to let us know if you have more questions!

**Closed by Linchin** 2024-01-31 23:48 UTC
Labels: type: question, status: will not fix, api: bigquery
