### ISSUE TITLE
pandas_gbq.to_gbq() return nulls everywhere

### ISSUE THREAD

**Issue by Mintactus** [googleapis/python-bigquery-pandas#779] opened 2024-06-04 18:06 UTC
Sorry to give limited informations about the bug but I have limited ressources and time:

Pandas 2.2.2

pandas_gbq.to_gbq()
When i use it, its just returns a bunch of null values for every columns, the original data as values from the dataframe I'm sending the data from.

Update: The issue is caused by bad columns names, it will import the columns with bad names in bigquery, with surprisly the name on it, but turns all the values of this column in nulls. I don't get it

**Comment by Linchin** [comment] 2024-06-04 23:44
Thank you @Mintactus for raising the issue. When you have time, could you provide a code snippet that reproduces the problem?

**Comment by Mintactus** [comment] 2024-06-05 00:17
Any dataframe with a header havings spaces in the names will trigger it if
i'm right

**Comment by Linchin** [comment] 2024-06-05 17:43
I'm unable to reproduce the issue - even with column names with space in it, the dataframe can be uploaded with no problem. For example:
```
import pandas as pd
from pandas_gbq import gbq

df = pd.DataFrame({' A a': [1, 2, 3], ' B b': [4, 5, 6]})
print(df)

gbq.to_gbq(df, destination_table='table_id', project_id='project_id', if_exists='replace')
```

Could you tell me more specifically in what condition the issue happens?

**Comment by tswast** [comment] 2024-06-18 21:04
@Linchin It might be that our test project has this preview feature enabled? https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-parquet#flexible-column-names

**Comment by Linchin** [comment] 2024-06-20 17:24
> @Linchin It might be that our test project has this preview feature enabled? https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-parquet#flexible-column-names

Wow thanks for the info! I'll disable preview and try again.

**Comment by Linchin** [comment] 2024-06-20 19:18
@Mintactus Indeed this will be resolved by the feature [flexible column names](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-parquet#flexible-column-names) once it is GA. The tentative time of GA is end of 2024 Q3. But for now, I think it is working as intended, and I suggest using column names with the [required format](https://cloud.google.com/bigquery/docs/schemas#column_names). I do think we should at least report an error, though.

**Comment by Mintactus** [comment] 2024-06-20 19:28
Thanks for the feedback, really apprieciated

**Closed** 2024-06-21 23:24 UTC
Labels: type: bug, priority: p3, api: bigquery
