### ISSUE TITLE
Pandas-gbq falsely claiming an invalid schema

### ISSUE THREAD

**Issue by matthew-kaye** [googleapis/python-bigquery-pandas#390] opened 2021-09-23 13:05 UTC
**Is your feature request related to a problem? Please describe.**
It's frustrating to get the `Error: Please verify that the structure and data types in the DataFrame match the schema of the destination table.` with no clarity as to what it is (from what I can see it's a perfect match), so I'd like an easy way to see more details, like I get when using the standard bigquery library (where things are working much better)

**Describe the solution you'd like**
An easier way to see logs. The instructions to import the logger and set logging level to debug aren't working for me.

**Describe alternatives you've considered**

**Comment by tswast** [comment] 2021-09-24 17:09
Thanks for the feedback! I agree that this error message is frustrating and can be better.

There is a PR from a contributor that makes a good start on this in https://github.com/googleapis/python-bigquery-pandas/pull/350 Once I have some time, I'll take a look at what we need to get it merged.

**Comment by tswast** [comment] 2021-09-24 17:11
I'll mark this as a duplicate of https://github.com/googleapis/python-bigquery-pandas/issues/349

**Closed by tswast** 2021-09-24 17:11 UTC
Labels: type: feature request, priority: p3, api: bigquery
